### ISSUE TITLE
Gallery publishing

### ISSUE THREAD

**Issue by fmartingr** [fmartingr/games-screenshot-manager#26]
Allow the gallery to be published automatically on being built. 

As a first step, we could allow the gallery to be uploaded using rsync to a remote server (which is my current approach). We could allow a parameter in the configuration so users build their own upload methods, or streamline the execution by implementing those ourselves.

Examples:
```toml
[gallery.publish]
enabled = true
command = "rsync -avz {{.GaleryFolder}} user@server:/var/www"
```

```toml
[gallery.publish.rsync]
user = "user"
host = "host"
remote_path = "/var/www"
```
